config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :villas

  resources :countries

  resources :areas

  resources :continents

  resources :static_pages

  resources :sections

  resources :regions

  resources :testimonials

  resources :popular_destinations

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'home#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/area.rb
class Area < ActiveRecord::Base
  belongs_to :region
  has_many :villas
  has_one :popular_destination
end

app/models/continent.rb
class Continent < ActiveRecord::Base
  has_many :countries
  has_many :villas
end

app/models/country.rb
class Country < ActiveRecord::Base
  belongs_to :continent
  has_many :regions
  has_many :villas
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
  validates_formatting_of :email, using: :email
end

app/models/need_to_know.rb
class NeedToKnow < ActiveRecord::Base
  belongs_to :villa
end

app/models/region.rb
class Region < ActiveRecord::Base
  belongs_to :country
  has_many :villas
  has_many :areas
  has_one :popular_destination
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :static_page
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  has_many :sections
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/villa.rb
class Villa < ActiveRecord::Base
  belongs_to :area
  belongs_to :region
  belongs_to :country
  belongs_to :continent
end

app/models/villa_detail.rb
class VillaDetail < ActiveRecord::Base
  belongs_to :villa
end

app/models/villa_rate.rb
class VillaRate < ActiveRecord::Base
  belongs_to :villa
  belongs_to :country
end

app/models/what_we_love.rb
class WhatWeLove < ActiveRecord::Base
  belongs_to :villa
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_static_page, only: [:show, :edit, :update, :destroy]

  # GET /static_pages
  # GET /static_pages.json
  def index
    @static_pages = StaticPage.all
  end

  # GET /static_pages/1
  # GET /static_pages/1.json
  def show
  end

  # GET /static_pages/new
  def new
    @static_page = StaticPage.new
  end

  # GET /static_pages/1/edit
  def edit
  end

  # POST /static_pages
  # POST /static_pages.json
  def create
    @static_page = StaticPage.new(static_page_params)

    respond_to do |format|
      if @static_page.save
        format.html { redirect_to @static_page, notice: 'Static page was successfully created.' }
        format.json { render :show, status: :created, location: @static_page }
      else
        format.html { render :new }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /static_pages/1
  # PATCH/PUT /static_pages/1.json
  def update
    respond_to do |format|
      if @static_page.update(static_page_params)
        format.html { redirect_to @static_page, notice: 'Static page was successfully updated.' }
        format.json { render :show, status: :ok, location: @static_page }
      else
        format.html { render :edit }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1
  # DELETE /static_pages/1.json
  def destroy
    @static_page.destroy
    respond_to do |format|
      format.html { redirect_to static_pages_url, notice: 'Static page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_page
      @static_page = StaticPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_page_params
      params.require(:static_page).permit(:name, :description)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/villas_helper.rb
module VillasHelper
end

app/views/static_pages/_form.html.erb
<%= form_for @static_page, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  static_pages_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/static_pages/edit.html.erb
<%- model_class = StaticPage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => StaticPage %></h1>
</div>
<%= render :partial => 'form' %>

app/views/static_pages/index.html.erb
<%- model_class = StaticPage -%>
<div class="page-header">
  <h1><%=t '.title', :default => StaticPage %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @static_pages.each do |static_page| %>
      <tr>
        <td><%= static_page.id %></td>
        <td><%= static_page.name %></td>
        <td><%= static_page.description %></td>
        <td><%=l static_page.created_at, format: :long %></td>
        <td>
          <%= link_to static_page_path(static_page), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to static_page_path(static_page), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_static_page_path,
            :class => 'btn btn-primary' %>

app/views/static_pages/new.html.erb
<%- model_class = StaticPage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => StaticPage %></h1>
</div>
<%= render :partial => 'form' %>

app/views/static_pages/show.html.erb
<%- model_class = StaticPage -%>
<div class="page-header">
  <h1><%=t '.title', :default => StaticPage %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @static_page.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @static_page.description %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              static_pages_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_static_page_path(@static_page), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              static_page_path(@static_page),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>