config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :villas

  resources :countries

  resources :areas

  resources :continents

  resources :static_pages

  resources :sections

  resources :regions

  resources :testimonials

  resources :popular_destinations

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'home#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/area.rb
class Area < ActiveRecord::Base
  belongs_to :region
  has_many :villas
  has_one :popular_destination
end

app/models/continent.rb
class Continent < ActiveRecord::Base
  has_many :countries
  has_many :villas
end

app/models/country.rb
class Country < ActiveRecord::Base
  belongs_to :continent
  has_many :regions
  has_many :villas
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
  validates_formatting_of :email, using: :email
end

app/models/need_to_know.rb
class NeedToKnow < ActiveRecord::Base
  belongs_to :villa
end

app/models/region.rb
class Region < ActiveRecord::Base
  belongs_to :country
  has_many :villas
  has_many :areas
  has_one :popular_destination
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :static_page
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  has_many :sections
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/villa.rb
class Villa < ActiveRecord::Base
  belongs_to :area
  belongs_to :region
  belongs_to :country
  belongs_to :continent
end

app/models/villa_detail.rb
class VillaDetail < ActiveRecord::Base
  belongs_to :villa
end

app/models/villa_rate.rb
class VillaRate < ActiveRecord::Base
  belongs_to :villa
  belongs_to :country
end

app/models/what_we_love.rb
class WhatWeLove < ActiveRecord::Base
  belongs_to :villa
end

app/controllers/villas_controller.rb
class VillasController < ApplicationController
  before_action :set_villa, only: [:show, :edit, :update, :destroy]

  # GET /villas
  # GET /villas.json
  def index
    @villas = Villa.all
  end

  # GET /villas/1
  # GET /villas/1.json
  def show
  end

  # GET /villas/new
  def new
    @villa = Villa.new
  end

  # GET /villas/1/edit
  def edit
  end

  # POST /villas
  # POST /villas.json
  def create
    @villa = Villa.new(villa_params)

    respond_to do |format|
      if @villa.save
        format.html { redirect_to @villa, notice: 'Villa was successfully created.' }
        format.json { render :show, status: :created, location: @villa }
      else
        format.html { render :new }
        format.json { render json: @villa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /villas/1
  # PATCH/PUT /villas/1.json
  def update
    respond_to do |format|
      if @villa.update(villa_params)
        format.html { redirect_to @villa, notice: 'Villa was successfully updated.' }
        format.json { render :show, status: :ok, location: @villa }
      else
        format.html { render :edit }
        format.json { render json: @villa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /villas/1
  # DELETE /villas/1.json
  def destroy
    @villa.destroy
    respond_to do |format|
      format.html { redirect_to villas_url, notice: 'Villa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_villa
      @villa = Villa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def villa_params
      params.require(:villa).permit(:name, :description, :guest_count, :bedroom_count, :villa_detail_heading, :love_points_heading, :villa_rates_heading, :need_to_know_heading, :feature_and_facility_heading, :similar_villas, :published, :area_id, :region_id, :country_id, :continent_id)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/continents_helper.rb
module ContinentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/villas_helper.rb
module VillasHelper
end

app/views/villas/_form.html.erb
<%= form_for @villa, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :guest_count, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :guest_count, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :bedroom_count, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :bedroom_count, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :villa_detail_heading, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :villa_detail_heading, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :love_points_heading, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :love_points_heading, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :villa_rates_heading, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :villa_rates_heading, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :need_to_know_heading, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :need_to_know_heading, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :feature_and_facility_heading, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :feature_and_facility_heading, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :similar_villas, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :similar_villas, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :published, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :published, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  villas_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/villas/edit.html.erb
<%- model_class = Villa -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Villa %></h1>
</div>
<%= render :partial => 'form' %>

app/views/villas/index.html.erb
<%- model_class = Villa -%>
<div class="page-header">
  <h1><%=t '.title', :default => Villa %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:guest_count) %></th>
      <th><%= model_class.human_attribute_name(:bedroom_count) %></th>
      <th><%= model_class.human_attribute_name(:villa_detail_heading) %></th>
      <th><%= model_class.human_attribute_name(:love_points_heading) %></th>
      <th><%= model_class.human_attribute_name(:villa_rates_heading) %></th>
      <th><%= model_class.human_attribute_name(:need_to_know_heading) %></th>
      <th><%= model_class.human_attribute_name(:feature_and_facility_heading) %></th>
      <th><%= model_class.human_attribute_name(:similar_villas) %></th>
      <th><%= model_class.human_attribute_name(:published) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @villas.each do |villa| %>
      <tr>
        <td><%= villa.id %></td>
        <td><%= villa.name %></td>
        <td><%= villa.description %></td>
        <td><%= villa.guest_count %></td>
        <td><%= villa.bedroom_count %></td>
        <td><%= villa.villa_detail_heading %></td>
        <td><%= villa.love_points_heading %></td>
        <td><%= villa.villa_rates_heading %></td>
        <td><%= villa.need_to_know_heading %></td>
        <td><%= villa.feature_and_facility_heading %></td>
        <td><%= villa.similar_villas %></td>
        <td><%= villa.published %></td>
        <td><%=l villa.created_at, format: :long %></td>
        <td>
          <%= link_to villa_path(villa), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to villa_path(villa), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_villa_path,
            :class => 'btn btn-primary' %>

app/views/villas/new.html.erb
<%- model_class = Villa -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Villa %></h1>
</div>
<%= render :partial => 'form' %>

app/views/villas/show.html.erb
<%- model_class = Villa -%>
<div class="page-header">
  <h1><%=t '.title', :default => Villa %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @villa.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @villa.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:guest_count) %></dt>
      <dd><pre class="prettyprint"><%= @villa.guest_count %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:bedroom_count) %></dt>
      <dd><pre class="prettyprint"><%= @villa.bedroom_count %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:villa_detail_heading) %></dt>
      <dd><pre class="prettyprint"><%= @villa.villa_detail_heading %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:love_points_heading) %></dt>
      <dd><pre class="prettyprint"><%= @villa.love_points_heading %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:villa_rates_heading) %></dt>
      <dd><pre class="prettyprint"><%= @villa.villa_rates_heading %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:need_to_know_heading) %></dt>
      <dd><pre class="prettyprint"><%= @villa.need_to_know_heading %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:feature_and_facility_heading) %></dt>
      <dd><pre class="prettyprint"><%= @villa.feature_and_facility_heading %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:similar_villas) %></dt>
      <dd><pre class="prettyprint"><%= @villa.similar_villas %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:published) %></dt>
      <dd><pre class="prettyprint"><%= @villa.published %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              villas_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_villa_path(@villa), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              villa_path(@villa),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>